### ISSUE TITLE
Preserve Case shows up in the Palette but doesn't work

### ISSUE THREAD

**Issue by mudit2103** [philippotto/Sublime-MultiEditUtils#26]
Hi,

Thank you for this awesome plug in! I have cloned this repo into the packages directory and it shows up on the palette. However, when I select a word, press Control+Command+G (to select all instances of that word), select Preserve Case in the palette, and then type the replacement for that word and press enter, nothing happens.

**Comment by philippotto** [comment]
Hi @mudit2103!

Which OS are you on and which Sublime Text version are you using? Can you open the console (View -> Show console) and try again? Maybe the console prints an error message.

Can you also provide a concrete example of what words you are selecting and what you input in the input box?

By the way, if you select all "exact" instances of a word and want to manipulate them, you don't really need the Preserve Case functionality. Since all words are equal you can just multi select and type.
The preserve case functionality is primarily useful for selecting words which differ in case.
But I misunderstood what you are trying to do :)

**Comment by mudit2103** [comment]
Hey,

I am using OSX El Capitan V 10.11.2
I am using Sublime Text 2.0.2

Yes, I understand that this is useful for when the words are in different cases; that is how I had them :)

There is indeed an error message on the console. I am pasting the entire console message from starting up Sublime. I am also attaching screenshot of the example that I'm trying to work with. I know that I can do this using the "Preserve Case" button on Sublime itself, but I do have some other cases where I have underscores and dots in the names.

## Screenshots
Selected "Egress"
![1](https://cloud.githubusercontent.com/assets/12883092/16775600/4269db78-4816-11e6-91ca-4a81eb716421.jpg)

Cmd+Shift+P -> Preserve 
![2](https://cloud.githubusercontent.com/assets/12883092/16775601/4269ff04-4816-11e6-9e3e-251379126f20.jpg)

Changed to ingress
![3](https://cloud.githubusercontent.com/assets/12883092/16775598/42694140-4816-11e6-92c5-6f121dbe02da.jpg)

Pressed enter, but nothing happened.
![4](https://cloud.githubusercontent.com/assets/12883092/16775599/4269d3a8-4816-11e6-85a6-70a09b50e573.jpg)




## Console error
```

startup, version: 2221 osx x64 channel: stable
executable: /Applications/Sublime Text 2.app/Contents/MacOS/Sublime Text 2
working dir: /
packages path: /Users/muditgupta/Library/Application Support/Sublime Text 2/Packages
settings path: /Users/muditgupta/Library/Application Support/Sublime Text 2/Settings
PackageSetup not required
catalogue loaded
found 5 files for base name Default.sublime-keymap
found 1 files for base name Default.sublime-mousemap
found 2 files for base name Main.sublime-menu
Reloading plugin /Users/muditgupta/Library/Application Support/Sublime Text 2/Packages/CSS/css_completions.py
Reloading plugin /Users/muditgupta/Library/Application Support/Sublime Text 2/Packages/Default/comment.py
Reloading plugin /Users/muditgupta/Library/Application Support/Sublime Text 2/Packages/Default/copy_path.py
Reloading plugin /Users/muditgupta/Library/Application Support/Sublime Text 2/Packages/Default/delete_word.py
Reloading plugin /Users/muditgupta/Library/Application Support/Sublime Text 2/Packages/Default/detect_indentation.py
Reloading plugin /Users/muditgupta/Library/Application Support/Sublime Text 2/Packages/Default/duplicate_line.py
Reloading plugin /Users/muditgupta/Library/Application Support/Sublime Text 2/Packages/Default/echo.py
Reloading plugin /Users/muditgupta/Library/Application Support/Sublime Text 2/Packages/Default/exec.py
Reloading plugin /Users/muditgupta/Library/Application Support/Sublime Text 2/Packages/Default/fold.py
Reloading plugin /Users/muditgupta/Library/Application Support/Sublime Text 2/Packages/Default/font.py
Reloading plugin /Users/muditgupta/Library/Application Support/Sublime Text 2/Packages/Default/goto_line.py
Reloading plugin /Users/muditgupta/Library/Application Support/Sublime Text 2/Packages/Default/indentation.py
Reloading plugin /Users/muditgupta/Library/Application Support/Sublime Text 2/Packages/Default/kill_ring.py
Reloading plugin /Users/muditgupta/Library/Application Support/Sublime Text 2/Packages/Default/mark.py
Reloading plugin /Users/muditgupta/Library/Application Support/Sublime Text 2/Packages/Default/new_templates.py
Reloading plugin /Users/muditgupta/Library/Application Support/Sublime Text 2/Packages/Default/open_file_settings.py
Reloading plugin /Users/muditgupta/Library/Application Support/Sublime Text 2/Packages/Default/open_in_browser.py
Reloading plugin /Users/muditgupta/Library/Application Support/Sublime Text 2/Packages/Default/paragraph.py
Reloading plugin /Users/muditgupta/Library/Application Support/Sublime Text 2/Packages/Default/save_on_focus_lost.py
Reloading plugin /Users/muditgupta/Library/Application Support/Sublime Text 2/Packages/Default/scroll.py
Reloading plugin /Users/muditgupta/Library/Application Support/Sublime Text 2/Packages/Default/set_unsaved_view_name.py
Reloading plugin /Users/muditgupta/Library/Application Support/Sublime Text 2/Packages/Default/side_bar.py
Reloading plugin /Users/muditgupta/Library/Application Support/Sublime Text 2/Packages/Default/sort.py
Reloading plugin /Users/muditgupta/Library/Application Support/Sublime Text 2/Packages/Default/swap_line.py
Reloading plugin /Users/muditgupta/Library/Application Support/Sublime Text 2/Packages/Default/switch_file.py
Reloading plugin /Users/muditgupta/Library/Application Support/Sublime Text 2/Packages/Default/transform.py
Reloading plugin /Users/muditgupta/Library/Application Support/Sublime Text 2/Packages/Default/transpose.py
Reloading plugin /Users/muditgupta/Library/Application Support/Sublime Text 2/Packages/Default/trim_trailing_white_space.py
Reloading plugin /Users/muditgupta/Library/Application Support/Sublime Text 2/Packages/Diff/diff.py
Reloading plugin /Users/muditgupta/Library/Application Support/Sublime Text 2/Packages/HTML/encode_html_entities.py
Reloading plugin /Users/muditgupta/Library/Application Support/Sublime Text 2/Packages/HTML/html_completions.py
Reloading plugin /Users/muditgupta/Library/Application Support/Sublime Text 2/Packages/Sublime-MultiEditUtils/MultiEditUtils.py
Reloading plugin /Users/muditgupta/Library/Application Support/Sublime Text 2/Packages/Sublime-MultiEditUtils/selection_fields.py
plugin init time: 0.121906
loading bindings
loading pointer bindings
found 1 files for base name Default.sublime-theme
theme loaded
app ready
pre session restore time: 0.387464
using gpu buffer for window
using gamma: 1.9 (err: 99.6544)
startup cache, total files: 97 cache hits: 97
startup time: 0.470349 (package setup was not run)
loaded 837 snippets
Traceback (most recent call last):
  File "./sublime_plugin.py", line 356, in run_
  File "./MultiEditUtils.py", line 253, in run
Boost.Python.ArgumentError: Python argument types in
    Region.__init__(Region, float, float)
did not match C++ signature:
    __init__(_object*, long long)
    __init__(_object*, long long, long long, double)
    __init__(_object*, long long, long long)
```

**Comment by philippotto** [comment]
> Yes, I understand that this is useful for when the words are in different cases; that is how I had them :)

Great! I just wanted to make sure we are on the same page.

I'm afraid this issue is ST2 and OS X specific. From what I've read, the necessary casting from `float` to `long long` should be done automatically by boost.
As a dirty workaround you could try to replace this line

```self.savedSelection = [sublime.Region(r[0], r[1]) for r in selections]```

in https://github.com/philippotto/Sublime-MultiEditUtils/blob/master/MultiEditUtils.py#L253 by

```self.savedSelection = [sublime.Region(long(r[0)], long(r[1])) for r in selections]```

Or, instead of using `long` you could also try to do `from ctypes import c_longlong as ll` and use `ll` for longlong. I would try it, but cannot reproduce it, unfortunately.

However, I think the better solution would be to upgrade to Sublime Text 3, if you are willing to do that. This should also fix the issue :)

**Comment by farmerpaul** [comment]
That fix works great; there's a small typo in your revision of line 253 though, some misplaced brackets. The line should be:

`self.savedSelection = [sublime.Region(long(r[0]), long(r[1])) for r in selections]`

I just edited the file directly under `~/Library/Application Support/Sublime Text 2/Packages/MultiEditUtils`, deleted `MultiEditUtils.pyc` and restarted Sublime Text (to be safe, since I'm not familiar with Python compilation or anything like that), and it worked.

**Comment by philippotto** [comment]
Thanks @farmerpaul, I updated my comment!
